#!/usr/bin/env ruby
$: << File.expand_path(File.join(File.dirname(__FILE__),'..','lib'))

require 'rz/client'

class Client
  include RZ::Client

  def run
    yield self
  ensure
    zmq_cleanup
  end

  def initialize
    initialize_client(
      :service_address => 'tcp://127.0.0.1:4000', 
      :identity => "client.#{Process.pid}"
    )
  end
end

Client.new.run do |client|
  puts 'executing 1000 asynchronous requests'

  1000.times do |i|
    client.request :eval, "sleep 1; #{i}"
  end

  puts 'receiving answers'

  a = Time.now

  1000.times do |i|
    x = client.receive :timeout => 1000
    p "x: #{x} i: #{i}"
  end

   b = Time.now

   puts "did work in: #{b-a} seconds"
end
