#!/usr/bin/env ruby
$: << File.expand_path(File.join(File.dirname(__FILE__),'..','lib'))

require 'rz/client'

class Client
  include RZ::Client

  def run
    yield self
  ensure
    zmq_cleanup
  end

  def initialize
    initialize_client :peer_address => 'tcp://127.0.0.1:4000', :identity => 'client'
  end
end

Client.new.run do |client|
  puts 'executing 1000 asynchronous requests'

  1000.times do |i|
    client.request :echo, i
  end

  puts 'waiting 10 seconds'

  sleep 10

  puts 'receiving answers'

  1000.times do |i|
    x = client.receive :timeout => 1000
    x = x.first
    p "x: #{x} i: #{i}"
  end
end
