#!/usr/bin/env ruby

require File.expand_path('../example',__FILE__)

services = Hash[[:a,:b,:c].map { |name| [name,Example.addresses.fetch(name).fetch(:frontend_address)] }]

options = {
  :services => services,
  :identity => "client-#{Process.pid}"
}

Client.new(options).run do |client|
  services.keys.each do |service|
    count = 10
    puts "executing #{count} asynchronous requests to service #{service}"

    count.times do |i|
      client.request service, { :name => :eval, :arguments => ["sleep 1; #{i}"], :job_id => i}
    end


    a = Time.now

    puts "receiving answers from service #{service}"

    count.times do |i|
      x = client.receive service, :timeout => 100
      puts "x: #{x} i: #{i}"
    end

    b = Time.now

    puts "did work in: #{b-a} seconds"
  end
end
