#!/usr/bin/env ruby
$: << File.expand_path(File.join(File.dirname(__FILE__),'..','lib'))

require 'rz/worker'

class Worker
  include RZ::Worker

  def initialize
    initialize_worker(
      :response_address   => 'tcp://127.0.0.1:4001',
      :request_address_a => 'tcp://127.0.0.1:4002', 
      :request_address_b => 'tcp://127.0.0.1:4003', 
      :identity => "worker#{Process.pid}"
    )
  end
end

Worker.send :register,:eval do |string|
  eval string
end

Worker.new.run
