#!/usr/bin/env ruby

require File.expand_path('../example',__FILE__)

name = ARGV[0] || raise("Usage ./worker {a,b,c}")


options = Example.options_for(:worker,ARGV[0].to_sym)

Worker.new(options).run
